spring :
    datasource:
        password: 100%Girlisperfect
        url: jdbc:postgresql://demodb.czvg23fov2bw.us-east-1.rds.amazonaws.com/5432/demodb
        username: wint
    jpa:
        hibernate :
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                dialect:org.hibernate.dialect.PostgreSQLDialect

